In [43]:
import pandas as pd

In [47]:
url = 'https://en.wikipedia.org/wiki/List_of_largest_sports_contracts'
tables = pd.read_html(url)

In [48]:
len(tables)

3

In [52]:
df= tables[0]

In [58]:
df

,Rank,Name,Organization,Sport,Length of contract,Contract value (USD),Average per year (USD),Average per game/event[a] (USD),Ref.
0,1,Lionel Messi,FC Barcelona,Association football,4 years (2017–2021),"$674,000,000","$168,500,000","$4,434,210 [b]",[1]
1,2,Cristiano Ronaldo,Al-Nassr,Association football,2.5 years (2023–2025)[c],"$536,336,818","$214,534,727","$7,151,158[d]",NaN
2,3,Patrick Mahomes[e]‡,Kansas City Chiefs,American football,10 years (2020–2031),"$450,000,000","$45,000,000","$2,465,686[f]",[2]
3,4,Mike Trout,Los Angeles Angels,Baseball,12 years (2019–2030),"$426,500,000","$35,541,667","$219,393",[3]
4,5,Canelo Álvarez,DAZN*,Boxing,5 years (2018–2023),"$365,000,000","$73,000,000","$33,181,818",[4]
...,...,...,...,...,...,...,...,...,...
94,96,Chris DavisR,Baltimore Orioles*,Baseball,7 years (2016–2022),"$161,000,000","$23,000,000","$141,975",[93]
95,97,Manny RamírezR,Boston Red Sox*,Baseball,8 years (2001–2008),"$160,000,000","$20,000,000","$123,456",[94]
96,98,Matt KempR,Los Angeles Dodgers*,Baseball,8 years (2012–2019),"$160,000,000","$20,000,000","$123,456",[95]
97,99,Dak Prescott‡,Dallas Cowboys,American football,4 years (2021–2024)[q],"$160,000,000","$40,000,000","$2,352,941[f]",[96]
98,100,Matthew Stafford‡,Los Angeles Rams,American football,4 years (2022–2026),"$160,000,000","$40,000,000","$2,352,941[f]",[97]

In [59]:
df.to_csv('Sports Contract')